# Metroretro API config
metroretro:
  # Content of the metret.sess cookie.
  session: some session
  # Content of the metret.sess.sig cookie. Needs to be renewed every 7 days.
  session_sig: some signature

# Sections to print in the formatted output.
# Any section without any note will be ignored.
sections:
  - Good
  - Bad
  - Actions

# Optional: upload the markdown content to a secret GitHub Gist instead of printing it
# in the terminal.
github:
  # GitHub username.
  username: jdoe
  # Access token with the "gist" scope.
  access_token: secret